// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitedYouthOrchestra7.Data;

namespace UnitedYouthOrchestra7.Migrations
{
    [DbContext(typeof(UnitedYouthOrchestra7Context))]
    partial class UnitedYouthOrchestra7ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnitedYouthOrchestra7.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("instrument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("UnitedYouthOrchestra7.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstFK")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SYearFK")
                        .HasColumnType("int");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstFK");

                    b.HasIndex("SYearFK");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("UnitedYouthOrchestra7.Models.Schoolyear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Other")
                        .HasColumnType("bit");

                    b.Property<bool>("Year10")
                        .HasColumnType("bit");

                    b.Property<bool>("Year11")
                        .HasColumnType("bit");

                    b.Property<bool>("Year12")
                        .HasColumnType("bit");

                    b.Property<bool>("Year13")
                        .HasColumnType("bit");

                    b.Property<bool>("Year6orEarlier")
                        .HasColumnType("bit");

                    b.Property<bool>("Year7")
                        .HasColumnType("bit");

                    b.Property<bool>("Year8")
                        .HasColumnType("bit");

                    b.Property<bool>("Year9")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Schoolyear");
                });

            modelBuilder.Entity("UnitedYouthOrchestra7.Models.Member", b =>
                {
                    b.HasOne("UnitedYouthOrchestra7.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnitedYouthOrchestra7.Models.Schoolyear", "Schoolyear")
                        .WithMany()
                        .HasForeignKey("SYearFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
